# SPI data availability

In [1]:
%load_ext jupyter_black
%load_ext autoreload
%autoreload 2

In [66]:
import datetime
import requests

import pandas as pd
from tqdm.notebook import tqdm

In [57]:
CPC_BASE_URL = "https://storage.googleapis.com/noaa-nidis-drought-gov-data/datasets/cog/v1"

In [70]:
start_date = datetime.date(2023, 1, 1)
end_date = datetime.date.today()
dates = pd.date_range(start_date, end_date, freq="D")

In [71]:
dicts = []
for date in tqdm(dates):
    date_str = date.strftime("%Y-%m-%d")
    date_url = f"{CPC_BASE_URL}/{date.year}/{date_str}"
    era5_filename = f"GLOBAL-ERA5-spi-1mo-{date_str}.tif"
    cmorph_filename = f"GLOBAL-NOAA_CPC_DAILY_GLOBAL-spi-1mo-{date_str}.tif"
    era5_url = f"{date_url}/{era5_filename}"
    cmorph_url = f"{date_url}/{cmorph_filename}"
    era5_response = requests.head(era5_url)
    cmorph_response = requests.head(cmorph_url)
    dicts.append(
        {
            "date": date,
            "era5": era5_response.status_code == 200,
            "cmorph": cmorph_response.status_code == 200,
        }
    )

df = pd.DataFrame(dicts)

  0%|          | 0/424 [00:00<?, ?it/s]

In [84]:
df.groupby([df["date"].dt.year, df["date"].dt.month]).mean(numeric_only=True)

               era5    cmorph
date date
2023 1     0.000000  0.000000
     2     0.000000  0.000000
     3     0.000000  0.000000
     4     0.000000  0.000000
     5     0.870968  0.806452
     6     0.333333  0.433333
     7     0.354839  0.225806
     8     0.548387  0.612903
     9     0.900000  0.800000
     10    0.290323  0.741935
     11    0.000000  0.100000
     12    0.548387  0.483871
2024 1     0.838710  0.903226
     2     0.678571  0.821429

In [86]:
df.iloc[-20:]

          date   era5  cmorph
404 2024-02-09   True    True
405 2024-02-10   True    True
406 2024-02-11   True    True
407 2024-02-12   True    True
408 2024-02-13   True    True
409 2024-02-14   True    True
410 2024-02-15   True    True
411 2024-02-16   True    True
412 2024-02-17  False    True
413 2024-02-18   True    True
414 2024-02-19   True    True
415 2024-02-20   True    True
416 2024-02-21  False    True
417 2024-02-22  False    True
418 2024-02-23  False    True
419 2024-02-24  False   False
420 2024-02-25  False   False
421 2024-02-26  False   False
422 2024-02-27  False   False
423 2024-02-28  False   False